Add example Gauge Taiko tests (#8)
* Install nodejs on devcontainer

We need nodejs for running the automated [Gauge][1] / [Taiko][2] tests
that we are about to add.

[1]: https://gauge.org/
[2]: https://taiko.dev/

* Install Gauge on devcontainer

* Add Chromium on devcontainer

We need Chromium to run the Taiko tests that we will be addding.

* Add default Gauge Taiko tests

These tests and associated files were all created by running:
`gauge init js`.

* Fix tests configuration on devcontainer

* Fix RuboCop Ruby linting by excluding Gauge files

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -7,11 +7,23 @@ ARG NODE_VERSION="none"
 RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
 
 # [Optional] Uncomment this section to install additional OS packages.
-# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-#     && apt-get -y install --no-install-recommends <your-package-list-here>
+ARG CHROMIUM_VERSION="none"
+ RUN if [ "${CHROMIUM_VERSION}" != "none" ]; then apt-get update && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -y install --no-install-recommends chromium="${CHROMIUM_VERSION}" \
+# Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*; fi
 
 # [Optional] Uncomment this line to install additional gems.
 RUN gem install bundler rubocop
 
 # [Optional] Uncomment this line to install global node packages.
 # RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
+
+# Install gauge and gauge plugins
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN curl -SsL https://downloads.gauge.org/stable | sh \
+    && su vscode -c "gauge install html-report" \
+    && su vscode -c "gauge install screenshot" \
+    && su vscode -c "gauge install js"
